language: php

php:
  - 7.2
  - 7.3
#  - 7.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install --dev

script:
  - bin/atoum -d tests/units

notifications:
  email:
    - info@fobofinist.ru
